# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180525_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
    ]
