# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180525_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('passsword', models.TextField()),
            ],
        ),
    ]
